### ISSUE TITLE
Short appendix on scientific plotting in tkinter

### ISSUE THREAD

**Issue by zunzun** [Dvlv/tkinter-book#1]
I have a tkinter application on github for curve fitting and surface fitting with matplotlib, the url on github is https://github.com/zunzun/tkInterFit - you might look it over and see if you want to use anything in your book.  The matplotlib 3D surface plots are mouse-rotatable and look really cool embedded in tkinter applications.

James
![screenshot](https://cloud.githubusercontent.com/assets/535821/25923229/224927ca-35a2-11e7-89b8-239c5b124717.png)

**Comment by Dvlv** [comment]
Thanks, I'll check it out
