### ISSUE TITLE
Can I translate your Tkinter book into Chinese?

### ISSUE THREAD

**Issue by newbietian** [Dvlv/tkinter-book#13]
Hi dude,
Your Tkinter book is really awesome!
Can I translate it into Chinese?
I will keep your name and add this Github site on it.
And If you approve, I will start translation and share the result with you when it is finished.

BRs,
PengTian

**Comment by Dvlv** [comment]
Yes, certainly.

**Comment by canberkozer** [comment]
Hello

Can I translate it into Turkish?

**Comment by Dvlv** [comment]
HI

Sure. 

I'll add a bit to the readme stating that people are free to translate it into another language, too.

**Comment by Dvlv** [comment]
Closing this issue now that there's a piece on the readme giving explicit permission. 

I will not lock it, so if you wish to link back to your translated versions here, you may.
