### ISSUE TITLE
(Chapter 2-1)The actual size of the window created is not the required size when invoking geometry

### ISSUE THREAD

**Issue by johnliao52** [Dvlv/tkinter-book#18]
In Chapter 2-1 the statement of self.geometry("300x400") created a window with the size of 300x400 in pixel.
But when I capture a snap screen and check it in mspaint, the actual window size is around 376x500, how to create a window with fixed size?

My platform is windows 10 64bit Home version, Python 3.7.4, Tkinter version 8.6.

**Comment by Dvlv** [comment]
Here on linux the window is the correct size.

Are you measuring the window borders and close/minimize/maximise buttons?
These are added by the OS (window manager) independent of tkinter. 
The size set by tkinter will be the inside contents of the window.

**Comment by johnliao52** [comment]
I mean just the client area which excludes the title bar, cclose/minimize/maximise buttons.
I tried in Ubuntu 15.10, Python 2.7.15, it is ok
