### ISSUE TITLE
Use a real monospace font

### ISSUE THREAD

**Issue by Kwpolska** [Dvlv/tkinter-book#2]
Computer Modern is a really good font, but code listings are meant to be written in a monospace font. This thing looks bad with uneven tracking, and no way to tell some characters apart.

Also, the .pdf file is hard to discover.

**Comment by Dvlv** [comment]
Font is corrected, let me know if you prefer it now.

The pdf is in the root of the repo, it's the only file besdies the readme. How would you suggest I make it more obvious?

**Comment by Kwpolska** [comment]
Link to it from the README.

That’s not what I expected. Computer Modern Roman is fine for body text. But code should be typeset in a monospace font. Not a sans font, not a serif font. See PR.

**Comment by nivaca** [comment]
Simply do this: 

Change line 30 from:

> basicstyle=\footnotesize

to:

> basicstyle=\ttfamily\footnotesize

I would also comment line 4:
> % \usepackage{helvet}

or replace it with a nicer font.

(Anyways, thanks for the book!)

**Comment by Kwpolska** [comment]
(PR #3 is concerned with that, and using DejaVu Sans Mono for mono text)

**Comment by Dvlv** [comment]
Thanks both of you for the help. You can likely tell this is my first Latex project!

The fonts should be all sorted now, and I've added a link in the README.

**Comment by Kwpolska** [comment]
One more TeX hint, by the way: don’t use \vspace{5mm} all over the document, just set up the `parskip` package.

**Comment by Dvlv** [comment]
Thanks Kwpolska

**Comment by nivaca** [comment]
@Kwpolska I would prefer to use `\bigskip` rather, if really needed.
