### ISSUE TITLE
Suggestion - new documentation for syntax-related issues

### ISSUE THREAD

**Issue by xonoma** [Dvlv/tkinter-book#5]
The code is lovely and self-documenting.  

However, there are some syntax choices that may raise questions -- e.g. the difference between _pack_propagate(0)_ and _pack_, the use of _ntpath_ instead of _os.path_, and others. 

As this is a by-example guide, I suggest the creation of a separate Markdown readme file to briefly describe why some of the code choices were made. It should not be a full-blown documentation, just a simple summary of those parts that may potentially confuse, why it was coded that way, and if necessary, some further references for more extended reading. I am happy to help out.

**Comment by Dvlv** [comment]
Hi xonoma
Thanks for the suggestion.
Since it's me who wrote the code and made all of the decisions, it's hard to determine what people may find confusing or questionable. If you could provide me with a list of what you would suggest I clarify that would be great.
