### ISSUE TITLE
Tablet friendly formats 

### ISSUE THREAD

**Issue by memilanuk** [Dvlv/tkinter-book#6]
Could we get a tablet-friendly PDF with narrow borders, and/or epub / mobi formats for e-readers?  Eloquentjavascript.net has some good examples near the bottom of the home page, with their github page located [here](https://github.com/marijnh/Eloquent-Javascript).

**Comment by Dvlv** [comment]
Aded .mobi and .epub into the assets folder and linked to them from the README.

If you have access to FBReader and its PDF plugin I would recommend that, as it looks great from my tablets like that.

**Comment by memilanuk** [comment]
I do have FBreader... it doesn't seem to play nice with PDFs when the
device is rotated to landscape... doesn't auto-expand/flow like Adobe
Reader does.

Thanks for the epub version, though!

**Comment by memilanuk** [comment]
Ummm... the TOC in the epub version appears a bit out of whack....
 Not sure if you can see it or not, but the TOC somehow ended up at the
*end* of the document.

**Comment by Dvlv** [comment]
Epub should have them at the beginning now. 
Mobi won't play ball, and I have no more ideas on how to fix it.
