### ISSUE TITLE
Text index positioning - x.y vs line.column

### ISSUE THREAD

**Issue by xonoma** [Dvlv/tkinter-book#7]
To my understanding, Tkinter's Text index syntax is "_line.column_" - e.g. "3.2" stands for line 3, column 2.

1. See first source - [effbot](http://effbot.org/tkinterbook/text.htm):

> line/column indexes are the basic index type. They are given as strings consisting of a line number and column number, separated by a period. Line numbers start at 1, while column numbers start at 0, like Python sequence indexes. You can construct indexes using the following syntax:

    "%d.%d" % (line, column)

2. See also [Text widget indices](http://infohost.nmt.edu/tcc/help/pubs/tkinter/web/text-index.html):

> An index is a general method of specifying a position in the content of a text widget. An index is a string with one of these forms:
> 
> 'line.column'
> The position just before the given column (counting from zero) on the given line (counting from one). Examples: '1.0' is the position of the beginning of the text; '2.3' is the position before the fourth character of the second line.

---------------------------

However, in **Chapter/Para 6.13** of _Tkinter by Example_, you wrote:

> We begin by grabbing the current index of the cursor with index(tk.INSERT) . This is returned in a string of the format "x.y". For example, the first character of the second line is "1.2" and the 14th character of line 12 is "14.12". The reason we need this is to try and grab the word which is currently being typed by the user. We need to go back one character in order to do this, which is where adjust_floating_index comes in.

The above indicates that the column/character comes first, then only line; i.e. it becomes _column.line_ instead of _line.column_. 

Is there an issue with the explanation, or is my understanding incorrect?

**Comment by Dvlv** [comment]
Hi Xonoma

The docs are definitely correct, thanks for spotting this, I will update the book when I get home.

Thanks buddy.

**Comment by Dvlv** [comment]
Main book is updated, will do mobile versions when I have time to fix tex4ebook again.

**Comment by xonoma** [comment]
No worries. Am going through the book back-to-back several times and doing all the exercises; they're very useful. Will let you know if I spot other issues.
