### ISSUE TITLE
`place` coordinates confusion: 300 vs. 500

### ISSUE THREAD

**Issue by Stigjb** [Dvlv/tkinter-book#8]
https://github.com/Dvlv/Tkinter-By-Example/blob/3ba79e8cf63d467a33682fe2264f90a3b83738aa/assets/Tkinter-By-Example.tex#L1326

The text and the code example seem to contradict each other, with the Y coordinate being 300 and 500, respectively

**Comment by Dvlv** [comment]
Thanks for your feedback. I will update this when I get home.

**Comment by Dvlv** [comment]
Fixed.
