### ISSUE TITLE
Tk inter Mac OS Quit ()

### ISSUE THREAD

**Issue by stef30360** [Dvlv/tkinter-book#9]
Hello,
I've got problem, I'm under mac os (High sierra), I'm searching how to close mainloop in tkinter windows. I'v tried .quit and .destroy but it doesn't work at all and  it makes the program crashing.
regards,
sr

**Comment by Dvlv** [comment]
Hi 
Calling destroy() on your Tk widget should close the window.
If it doesn't work, please post your code.

**Comment by stef30360** [comment]
Hi, thanks for your answer, in fact, it works on Windows  but not in OS mac.

` menu1.add_command(label="Quitter", command=fenetre1.destroy)`
